'use client';

import { motion } from 'framer-motion';
import { ArrowDown } from 'lucide-react';
import { comments } from '@/data/demoData';

export function Hero() {
  return <section id="inicio" className="noise grid-bg relative flex min-h-screen items-center overflow-hidden px-6"><div className="mx-auto grid w-full max-w-[1180px] items-center gap-16 pt-24 lg:grid-cols-[1.05fr_.95fr]"><div className="relative z-10"><motion.p initial={{ opacity: 0, y: 15 }} animate={{ opacity: 1, y: 0 }} className="eyebrow">Propuesta tecnológica</motion.p><motion.h1 initial={{ opacity: 0, y: 28 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .1 }} className="display mt-6 max-w-2xl text-5xl sm:text-7xl">Cada comentario cuenta una historia.</motion.h1><motion.p initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .22 }} className="mt-7 max-w-xl text-2xl leading-relaxed text-slate-100">El verdadero reto es escuchar miles al mismo tiempo.</motion.p><p className="mt-5 max-w-lg text-base leading-7 text-slate-300">Una propuesta para transformar conversaciones en redes sociales en información organizada, medible y accionable.</p><a href="#problema" className="mt-9 inline-flex items-center gap-3 rounded-full bg-[#b7f170] px-6 py-3 text-base font-bold text-[#07111f] transition hover:scale-[1.03]">Explorar propuesta <ArrowDown size={17} /></a></div><div className="relative mx-auto h-[460px] w-full max-w-[470px]" aria-label="Comentarios digitales organizándose"><div className="animate-pulse-soft absolute left-1/2 top-1/2 h-44 w-44 -translate-x-1/2 -translate-y-1/2 rounded-full bg-[#b7f170]/10 blur-3xl" />{comments.map((comment, index) => <motion.div key={`${comment}-${index}`} animate={{ y: [0, (index % 3 - 1) * 14, 0], x: [0, (index % 2 ? 1 : -1) * 9, 0] }} transition={{ repeat: Infinity, duration: 4 + index % 3, delay: index * .15 }} className="panel absolute rounded-xl px-4 py-3 text-sm text-slate-100" style={{ left: `${8 + (index * 37) % 75}%`, top: `${5 + (index * 61) % 80}%`, transform: 'translate(-50%,-50%)' }}>{comment}</motion.div>)}<div className="absolute left-1/2 top-1/2 flex h-32 w-32 -translate-x-1/2 -translate-y-1/2 items-center justify-center rounded-full border border-[#b7f170]/50 bg-[#0b2031] text-center text-xs font-bold text-[#b7f170] shadow-[0_0_70px_rgba(183,241,112,.18)]">SEÑALES<br />CIUDADANAS</div></div></div></section>;
}
