'use client';

import { motion } from 'framer-motion';
import { ArrowDown, BrainCircuit, Database, Globe2, Layers3, Sparkles } from 'lucide-react';
import { categories, modules } from '@/data/demoData';

const reveal = { initial: { opacity: 0, y: 25 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true, amount: .25 }, transition: { duration: .65 } };

export function Problem() {
  const problemCategories = [...categories, { name: 'Comercio', value: 31, color: '#76b9ff' }];
  return <section id="problema" className="section bg-[#f7fafc] text-[#07111f]"><motion.div {...reveal} className="mx-auto max-w-[1180px]"><p className="eyebrow !text-[#1f6b55]">El problema</p><h2 className="display mt-6 max-w-3xl text-5xl sm:text-7xl">Hoy tenemos información.<br />Pero está dispersa.</h2><div className="mt-14 grid gap-10 lg:grid-cols-[.85fr_1.15fr]"><div><b className="text-7xl tracking-tighter sm:text-9xl">4.000</b><p className="mt-2 max-w-[240px] text-xl leading-8 text-slate-600">comentarios en una publicación.</p><p className="mt-8 text-2xl font-bold">¿Quién lee 4.000 comentarios?</p></div><div className="rounded-2xl border border-slate-200 bg-white p-6"><p className="data-note">Del caos al orden · demostración conceptual</p><div className="mt-8 grid grid-cols-2 gap-3 sm:grid-cols-3">{problemCategories.map((item) => <div key={item.name} className="rounded-xl border border-slate-100 p-4 transition-transform duration-300 hover:-translate-y-1"><span className="block h-2 w-2 rounded-full" style={{ background: item.color }} /><b className="mt-5 block text-base">{item.name}</b><span className="text-sm text-slate-500">señal identificable</span></div>)}</div></div></div></motion.div></section>;
}

function Meta({ label, value }: { label: string; value: string }) { return <div><span className="block text-xs uppercase tracking-widest text-slate-400">{label}</span><b className="mt-1 block text-base text-slate-100">{value}</b></div>; }

export function Opportunity() { return <section className="section grid-bg"><div className="mx-auto grid max-w-[1180px] gap-12 lg:grid-cols-2"><motion.div {...reveal}><p className="eyebrow">La oportunidad</p><h2 className="display mt-6 text-5xl sm:text-6xl">Los comentarios no son solamente interacción.</h2><p className="mt-6 text-xl leading-8 text-slate-200">También pueden convertirse en información.</p></motion.div><motion.div {...reveal} className="panel rounded-2xl p-6 sm:p-8"><div className="rounded-lg bg-white/5 p-5 text-base leading-7 text-slate-100">“En el Limonar la calle 39 está acabada.”</div><div className="my-4 flex justify-center"><ArrowDown className="text-[#b7f170]" /></div><div className="grid grid-cols-2 gap-x-5 gap-y-5"><Meta label="Categoría" value="Infraestructura vial" /><Meta label="Ubicación" value="Limonar / Calle 39" /><Meta label="Tipo" value="Reporte ciudadano" /><Meta label="Sentimiento" value="Negativo" /><Meta label="Seguimiento" value="Recomendado" /></div></motion.div></div></section>; }

export function Architecture() {
  const steps = [['Facebook', Globe2, 'Fuente de información'], ['Meta Graph API', Layers3, 'Consulta autorizada'], ['Spring Boot', Database, 'Procesamiento automático'], ['Motor inteligente', BrainCircuit, 'Clasifica y organiza'], ['SQL / Base de datos', Database, 'Histórico sin reprocesos'], ['Dashboard', Sparkles, 'Información clara']] as const;
  return <section id="solucion" className="section bg-[#0b1d2c]"><div className="mx-auto max-w-[1180px]"><motion.div {...reveal}><p className="eyebrow">La solución conceptual</p><h2 className="display mt-6 text-5xl sm:text-7xl">De Facebook a<br />inteligencia ciudadana.</h2></motion.div><div id="funcionamiento" className="mt-16 grid gap-2 md:grid-cols-6">{steps.map(([name, Icon, description], index) => <div key={name} className="relative"><div className="panel min-h-44 rounded-xl p-5 transition-transform duration-300 hover:-translate-y-1"><Icon size={24} className="text-[#b7f170]" /><b className="mt-8 block text-base">{name}</b><p className="mt-2 text-sm leading-6 text-slate-300">{description}</p></div>{index < steps.length - 1 && <div className="absolute -right-2 top-1/2 z-10 hidden h-px w-4 bg-[#b7f170] md:block" />}</div>)}</div></div></section>;
}

export function Engine() { return <section className="section bg-white text-[#07111f]"><div className="mx-auto grid max-w-[1180px] gap-14 lg:grid-cols-[1fr_.9fr]"><motion.div {...reveal}><p className="eyebrow !text-[#1f6b55]">Motor inteligente</p><h2 className="display mt-6 text-5xl sm:text-6xl">El sistema hace el trabajo.</h2><p className="mt-6 max-w-lg text-xl leading-8 text-slate-600">4.000 comentarios no significan 4.000 registros manuales. El motor combina capas para entender palabras y contexto.</p></motion.div><motion.div {...reveal} className="rounded-2xl bg-[#07111f] p-6 text-white"><div className="grid grid-cols-3 gap-3">{['Reglas', 'Palabras clave', 'Inteligencia Artificial'].map((name, index) => <div key={name} className="rounded-xl border border-white/10 p-3 text-sm"><span className="text-[#b7f170]">0{index + 1}</span><b className="mt-4 block leading-5">{name}</b></div>)}</div><p className="mt-8 text-base leading-7 text-slate-200">“Por mi casa ya no se puede pasar cuando llueve.”</p><div className="mt-4 rounded-lg bg-[#b7f170] p-3 text-sm font-bold text-[#07111f]">Posible infraestructura vial · contexto detectado</div></motion.div></div></section>; }

export function ModulesRoadmap() { const roadmap = [['01', 'Conexión', 'Meta / Facebook'], ['02', 'Datos', 'Publicaciones + comentarios'], ['03', 'Inteligencia', 'Clasificación'], ['04', 'Dashboard', 'Visualización'], ['05', 'Gestión', 'Casos ciudadanos'], ['06', 'Automatización', 'Sincronización y alertas']]; return <section id="desarrollo" className="section"><div className="mx-auto max-w-[1180px]"><motion.div {...reveal}><p className="eyebrow">Desarrollo gradual</p><h2 className="display mt-6 text-5xl sm:text-6xl">Una ruta clara para validar.</h2><p className="mt-5 text-lg text-slate-300">Estimaciones preliminares, no compromiso contractual.</p></motion.div><div className="mt-14 grid gap-px overflow-hidden rounded-2xl bg-white/10 sm:grid-cols-2 lg:grid-cols-4">{modules.map((name, index) => <div key={name} className="bg-[#07111f] p-6 transition-colors hover:bg-[#0d2233]"><span className="text-sm text-[#b7f170]">0{index + 1}</span><h3 className="mt-10 text-lg font-bold">{name}</h3><p className="mt-2 text-sm leading-6 text-slate-300">Módulo preparado para una gestión más organizada.</p></div>)}</div><div className="mt-16 grid gap-5 md:grid-cols-3">{roadmap.map(([number, name, description], index) => <div className="flex items-center gap-4" key={number}><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full border border-[#b7f170] text-xs text-[#b7f170]">{number}</span><p className="text-base"><b>{name}</b><span className="block text-sm text-slate-300">{description}</span></p>{index < roadmap.length - 1 && <span className="hidden text-[#b7f170] md:block">→</span>}</div>)}</div></div></section>; }
